services:
  # ==========================================
  # KAFKA CLUSTER (Giữ nguyên phom chuẩn của em)
  # ==========================================
  kafka:
    # 1. Hàng chính chủ, có version đàng hoàng
    image: apache/kafka:3.7.0
    container_name: shibana-kafka

    # 1.1 BÙA CHÚ VƯỢT QUYỀN: Ép chạy bằng quyền Root để sửa lỗi AccessDenied
    user: "root"

    # 2. Mở đúng 1 cửa cho máy Host (IntelliJ, DataGrip) chọc vào
    ports:
      - "9092:9092"

    # 3. Gắn ổ cứng ảo bảo vệ data
    volumes:
      - kafka_data:/tmp/kafka-logs

    environment:
      # --- CỤM 1: CĂN CƯỚC & KRAFT (Không cần Zookeeper) ---
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      
      # --- CỤM 2: MẠNG LƯỚI TỐI GIẢN (Chỉ tiếp khách từ máy Host) ---
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT'

      KAFKA_LISTENERS: 'EXTERNAL://:9092,CONTROLLER://:9093,INTERNAL://:29092'
      KAFKA_ADVERTISED_LISTENERS: 'EXTERNAL://localhost:9092,INTERNAL://kafka:29092'

      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      
      # --- CỤM 3: BÙA CHÚ TỐI ƯU LOCAL (Chống báo lỗi & Hack tốc độ) ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-ui:
    image: kafbat/kafka-ui:latest
    container_name: shibana-kafka-ui
    ports:
      - "9090:8080"
    depends_on:
      - kafka # Đợi Kafka chạy lên trước rồi UI mới chạy
    environment:
      # Cấu hình theo đúng Docs của Provectus
      KAFKA_CLUSTERS_0_NAME: shibana-local-cluster
      # Trỏ đúng vào tên service "kafka" và cổng INTERNAL "29092" mà ta đã mở ở trên
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      # Ẩn các topic nội bộ của hệ thống cho đỡ rối mắt
      DYNAMIC_CONFIG_ENABLED: 'true'
    restart: unless-stopped

  # ==========================================
  # REDIS CLUSTER (Tốc độ ánh sáng cho Local)
  # ==========================================
  redis:
    image: redis:7.2-alpine
    container_name: shibana-redis
    ports:
      - "6379:6379"
    # 🚀 BÙA CHÚ: Ép Redis Local xài đúng cái Password Cloud của em để code khỏi phải sửa nhiều
    command: redis-server --requirepass 123123
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "123123", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

# Khai báo Volume
volumes:
  kafka_data:
  redis_data: